[tool.poetry]
name = "VozAtivaSystemMessage"
version = "0.0.1"
description = "*"
authors = ["Gustavo Isobe <gustavotavares1234@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
starlette = "^0.41.3"
uvicorn = "^0.23.2"
pydantic = "1.10.9"
gunicorn = "^21.2.0"
python-json-logger = "^3.2.0"
